### ISSUE TITLE
handlePacketEvent is triggered twice

### ISSUE THREAD

**Issue by iwinux** [joshgummersall/statsd-riemann-backend#1] opened 2014-12-31 03:05 UTC
Hi,

My StatsD (v0.7.2) config:

``` javascript
{
  debug: false,
  automaticConfigReload: false,
  backends: ["./node_modules/statsd-riemann-backend/index"],
  riemann: {
    host: 'riemann',
    port: 3009,
    transport: 'tcp',
  },
  prefixStats: 'statsd',
}
```

On every metric (e.g.: `echo "test:99|c" | nc -u -w0 localhost $port`), it crashes like this:

```
$ /opt/statsd/bin/statsd statsd.js                                       
31 Dec 11:01:50 - reading config file: statsd.js
31 Dec 11:01:50 - server is up
GOT event: test:99|c
GOT metric: 99|c
GOT event: 
GOT metric: undefined

/opt/statsd/node_modules/statsd-riemann-backend/lib/riemann.js:82
  return eventMetric.split('|')[0];
                     ^
TypeError: Cannot call method 'split' of undefined
    at Riemann.getMetric (/opt/statsd/node_modules/statsd-riemann-backend/lib/riemann.js:82:22)
    at Riemann.handlePacketEvent (/opt/statsd/node_modules/statsd-riemann-backend/lib/riemann.js:108:18)
    at /opt/statsd/node_modules/statsd-riemann-backend/node_modules/underscore/underscore.js:70:21
    at Function._.each._.forEach (/opt/statsd/node_modules/statsd-riemann-backend/node_modules/underscore/underscore.js:103:9)
    at Riemann.onPacket (/opt/statsd/node_modules/statsd-riemann-backend/lib/riemann.js:48:5)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (/opt/statsd/stats.js:195:21)
    at Socket.emit (events.js:98:17)
    at UDP.onMessage (dgram.js:441:8)
```

(The _GOT event/metric_ debug messages are added by myself)

**Comment by iwinux** [comment] 2014-12-31 03:17
Well, seems that `parsePacket` returns something unexpected:

```
GOT events: [ 'abc.test:99|c', '' ] # console.warn('GOT events:', this.parsePacket(packet))
GOT event: abc.test:99|c
GOT metric: 99|c
GOT event: 
GOT metric: undefined
```

**Comment by Recodify** [comment] 2015-01-03 19:09
This is being caused by the fact that the function parsePacket uses String.split to, I guess, support the sending of multiple metrics at the same time. When one metric is sent, for example foo:1|c, split('\n') will return ['foo:1|c', ''], this is the source of your two events/triggers. 

One fix for this is the amended function below:

Riemann.prototype.parsePacket = function(packet) {
  return packet.toString().split('\n').filter(function(el) {return el.length != 0});;
};

**Comment by iwinux** [comment] 2015-01-04 02:34
@samshiles yeah, you got it :)

**Comment by joshgummersall** [comment] 2015-03-12 19:26
Fixed.

**Closed as completed by joshgummersall** 2015-03-12 19:26 UTC
